tasks:
  - init: mvn install spring-boot:start spring-boot:stop
    command: mvn
github:
  prebuilds:
    # enable prebuilds for all branches in this repo
    branches: true 

vscode:
  extensions:
    - redhat.java