tasks:
  - init: mvn install -Pproduction && node_modules/.bin/webpack-dev-server | while read line; do if [[ $line == *"Compile"* ]] ; then pkill -9 -f webpack-dev-server ; fi ; done

    command: mvn
ports:
  - port: 8080
    onOpen: open-preview
