tasks:
  - init: mvn install -Pproduction && node_modules/.bin/webpack-dev-server | while read line; do if [[ $line == *"Compile"* ]] ; then kill -9 `ps a|grep webpack-dev-server|grep -v grep|cut -c1-8` ; fi ; done

    command: mvn
ports:
  - port: 8080
    onOpen: open-preview
