language: java
jdk: openjdk8
sudo: required
dist: xenial

before_install:
  # Disable all Travis default repositories
  - sed -i "s/activeByDefault>true</activeByDefault>false</g"  ~/.m2/settings.xml
  # Make it possible to run tests on a local Chrome
  - export CHROME_BIN=/usr/bin/google-chrome

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:
  - mvn -B -e -V clean verify -Pintegration-tests,production

# Cache requires a master build
branches:
  only:
    - master
    - ccdm
cache:
  directories:
  - $HOME/.m2
before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/flow
  - rm -rf $HOME/.m2/repository/com/vaadin/flow-*

